### ISSUE TITLE
how are you gonna get the private key in?

### ISSUE THREAD

**Issue by dominictarr** [du5t/capsule#1]
to make this work using ssb-client, it needs to load the private key and then make a full connection to the local instance. Currently, patchwork exposes a plaintext websocket connect to localhost only, so you could connect to that instead.

but maybe having that is problematic, if any website can make a websocket (cross origin by default) localhost connection? @pfraze ?

Otherwise, you need to load the (or, a) private key and connect with that. sbot also has a `master` config, which allows another private key to connect and have the authority of the main private key (so far, this is useful for getting a pub to follow people or create invites remotely) we could use that here though.

**Comment by du5t** [comment]
so emacs-server has a thing where it listens for traffic passed to it by a registered 'org-protocol' in modern browsers: http://orgmode.org/worg/org-contrib/org-protocol.html

> This one is triggered through the sub-protocol "capture" and consumes up to three data fields:
> 
> emacsclient org-protocol:/capture:/URL/TITLE/BODY
> will pop up an Capture buffer and fill the template with the data submitted.
> 
> To use this feature, add a bookmark with an arbitrary name (e.g. "Org: capture") and enter this as "Location":

``` js
javascript:location.href='org-protocol://capture://'+
      encodeURIComponent(location.href)+'/'+
      encodeURIComponent(document.title)+'/'+
      encodeURIComponent(window.getSelection())
```

> The result depends on the template used. See An example capture template further down.

this lets you pass info over to that server by running `emacsclient` (a background process), which then loads up a buffer in emacs proper with the input data and some UI stuff in a prompt set up on that side. i don't have a proof of concept, but the emacs side could always run a function with user confirmation that accesses filesystem data (like secret keys). notably, this bypasses any CORS/XSS protection, and keeps the browser from getting its fingers into the fs.

i really don't think it would be a good idea to write an ssb-client in emacs lisp, but the pieces kind of line up: browser, serialization protocol (org-protocol), client (emacsclient), server (emacs-server), and client-side app (emacs).

what do you think?

**Comment by pfrazee** [comment]
https://stackoverflow.com/questions/23674199/why-is-there-no-same-origin-policy-for-websockets-why-can-i-connect-to-ws-loc I didnt know that!

As they say in that stack overflow, we can enforce CORS ourselves using the Origin header. If we want to just deny non-patchwork clients for now, we can. I dont know what kind of origin header a chrome extension will have, though. I very much hope it'll have one... if it doesnt, then we may have a problem.

The other alternative is to make users set a password for Patchwork.

Registering a protocol with the OS is an interesting solution. We will likely want to register `ssb:` at some point, so we could use a similar sub-protocol, like `ssb:perms/...`, for granting access to the websocket. But, if Patchwork is sitting on a known port, then it may be enough to open `http://localhost:7777/perms/...`. Obviously a registered protocol would be better.

**Comment by du5t** [comment]
i feel like there are less wires to reach into with a protocol registration, and then it becomes an explicit negotiation with the user who can revoke things. a CORS list set by ssbc whose modifications have to be asked-for (or fork+upstream track) sounds more like having to phone a utility company to ask them to enable this or that 'service' with the pipe they maintain. ("hullo internet provider, i'd like the 'cypherspace application adapter' added to my plan, thank you.")

also, writing one addon for chromium, one for firefox, and then leaving all of the other browserites and http-stream parsing robot people out in the cold seems like a slog into slowly freezing mud :\ i only started off in that direction because it seemed like the shortest viable route.

firefox and chromium both seem to play nicely enough with new protocols, so it's a start:

![protocol-handler](https://cloud.githubusercontent.com/assets/14898482/14062077/ecd9b946-f34f-11e5-852b-e38433b3220c.png)
![protocol-handler2](https://cloud.githubusercontent.com/assets/14898482/14062099/66987e0c-f350-11e5-9658-41fecef6c6a3.png)

also, https://developers.google.com/web/updates/2011/06/Registering-a-custom-protocol-handler seems not-terrible.

here's a pair of items i suppose need tackling in order to make protocol registration useful:
- [x] protocol listener test for sbot sending
- [x] design and building of middleware (such as [ssbify](https://github.com/krl/ssbify)) into some larger protocol listener

i feel like there's a need for some 'protocol-listener' adapter here, since ssb-client has a very specific design like you mentioned above. do i have that right?

**Comment by pfrazee** [comment]
How are they different? A protocol and CORS management should both involve the same techniques. The protocol is an added step to what will have to happen with CORS, that changes what endpoint you speak to. Without the protocol, it will be something like `http://localhost:7777/perms`, and with the protocol it will be something like `ssb:perms`.

**Comment by du5t** [comment]
ahhh so you're saying that patchwork itself is enforcing CORS/XSS protection because it's the endpoint of a websocket? all of the handlers i mentioned above aren't part of that ecosystem--even emacsclient just gets registered thru xdg-open. i've never had to do any CORS fiddling with a non-webapp at the other end of a URI before.

since `sbot` is a CLI also, maybe [xdg-open/open](https://superuser.com/questions/911735/brew-install-xdg-utils) would be a quick shim thru the same route?

edit: for completeness, [msdn docs](https://msdn.microsoft.com/en-us/library/aa767914%28v=vs.85%29.aspx) on registering URI handlers with the OS.

**Comment by pfrazee** [comment]
I'll have to research it more deeply. I dont know if there's any advantage of using a different interface than the HTTP socket, yet.

**Comment by dominictarr** [comment]
the downside of relying on a header set by the browser is that you are assuming that the browser is the only source of incoming connections... which might be usually the case but doesn't feel guaranteed.

**Comment by pfrazee** [comment]
@dominictarr that's my concern as well. If there's another IO interface that has more consistent client identification, we should use that. Otherwise, if Host header isnt good enough, we may need the password scheme.

**Comment by du5t** [comment]
for your consideration, %5qdOJcHxltSS3BHYtQf1VeHCRG+/S7Uk3l7oCJ5mfYk=.sha256:

> @rainbro weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee; (post sent from xdg-open URI handler bookmarklet)

weeeeeeeeeeeeeeeeeeeeeeeeeeeeee

---

sent by an `xdg-open` registered script that reads:

```
sbot publish --type post --text "@rainbro weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee; (post sent from xdg-open URI handler bookmarklet)" --channel test
```

**Comment by dominictarr** [comment]
how would the "password" work?

(I think it would be better to use a cap system, where high entropy passwords are generated and then you can c/p them into apps, but other elements of such a design will probably be the same)

**Comment by pfrazee** [comment]
You put the WebSocket behind HTTP Basic Auth, or behind a login screen and use a session cookie (same effect, different UI -- in fact the latter would probably be better).

The problem is that single-origin policy doesn't work well on localhost. If there's any program that can circumvent the Origin header, then that program will be able to run a GET request on the Patchwork interface. So, we cant just inject a capability into the Patchwork html. The user needs to put in some kind of password.

I'd be okayish with a capability (the mechanism would be the same as for passwords). It'd be great if the OS provided a better mechanism.

We _would_ be able to create isolated channels between the node thread and UI if we use electron exclusively, because it has an IPC interface, which I'm fairly sure can't be accessed by outside programs.

**Comment by du5t** [comment]
closing because smuggling data out of the browser through a URI into the OS worked
